// M3 buy flow end to end through mock payments: UI + API. env BASE, SEED, DB, OUT, WT. Run on a limits-off instance (RATE_LIMIT_ENABLED=0).
import * as L from "./qa-fe5-lib.mjs"; import crypto from "node:crypto"; const { log, ok, usd, BASE, seed } = L;
const db = await L.dbc(); const b = await L.browser(); const link = seed.maya.links.studio; const dropId = (await db.query("select id from drops where public_link_id=$1", [link])).rows[0].id;
const post = async (path, body, h = {}) => { const r = await fetch(BASE + path, { method: "POST", headers: { "content-type": "application/json", origin: BASE, "x-forwarded-for": L.fakeIp(44), ...h }, body: typeof body === "string" ? body : JSON.stringify(body) }); const t = await r.text(); let j; try { j = JSON.parse(t); } catch {} return { s: r.status, j, t, h: r.headers }; };
const co = (o = {}, h = {}) => post("/api/checkout", { linkId: link, email: `qa-${crypto.randomBytes(3).toString("hex")}@example.test`, confirmOver18: true, ...o }, h);
log("== 1. server-side validation");
for (const [n, o, want] of [["missing confirmOver18", { confirmOver18: undefined }, 400], ["confirmOver18=false", { confirmOver18: false }, 400], ["confirmOver18='true'", { confirmOver18: "true" }, 400], ["confirmOver18=1", { confirmOver18: 1 }, 400], ["confirmOver18=null", { confirmOver18: null }, 400], ["email missing", { email: undefined }, 400], ["email 'nope'", { email: "nope" }, 400], ["email 'a@b'", { email: "a@b" }, 400], ["email with space", { email: "a b@example.test" }, 400], ["email 255 chars", { email: "a".repeat(250) + "@e.co" }, 400], ["email NUL", { email: "a\u0000@example.test" }, 400], ["email array", { email: ["a@example.test"] }, 400], ["email object", { email: { a: 1 } }, 400], ["email number", { email: 5 }, 400], ["both dropId+linkId", { dropId }, 400], ["bad linkId", { linkId: "short" }, 400], ["unknown linkId", { linkId: "zzzzzzzzzzzz" }, 404], ["extra amountCents ignored", { amountCents: 1, priceCents: 1, price: 1 }, 201], ["email padded trims", { email: "  pad@example.test  " }, 201]]) {
  const r = await co(o); ok(r.s === want && r.s < 500, `${n} -> ${r.s} ${r.j?.code ?? ""} ${(r.j?.error ?? "").slice(0, 60)}`); if (n.startsWith("extra")) ok(r.j.amountCents === 2500, "price from DB: amountCents 2500 despite client amount fields"); }
for (const [n, body] of [["bad JSON", "{not json"], ["empty body", ""], ["array body", "[]"], ["null body", "null"], ["string body", '"x"']]) { const r = await post("/api/checkout", body); ok(r.s === 400, `${n} -> ${r.s}`); }
{ const r = await fetch(BASE + "/api/checkout", { method: "POST", headers: { origin: BASE, "x-forwarded-for": L.fakeIp(44), "content-type": "text/plain" }, body: JSON.stringify({ linkId: link, email: "a@example.test", confirmOver18: true }) }); log("   text/plain content-type ->", r.status); ok(r.status < 500, "text/plain body not 5xx"); }
{ const r = await fetch(BASE + "/api/checkout", { method: "POST", headers: { origin: "https://evil.example", "content-type": "application/json", "x-forwarded-for": L.fakeIp(44) }, body: JSON.stringify({ linkId: link, email: "a@example.test", confirmOver18: true }) }); log("   foreign Origin ->", r.status); }
for (const st of ["draft", "unpublished"]) { const u = seed.maya.links[st === "draft" ? "draft" : "unpublished"]; const r = await co({ linkId: u }); ok(r.s === 404, `checkout for ${st} drop -> ${r.s}`); }
{ const ps = await db.query("select verification_status from sellers where email=$1", [seed.jo.email]); const jd = seed.jo.dropId; const r = await co({ linkId: undefined, dropId: jd }); ok(r.s >= 400 && r.s < 500, `checkout for pending-verification seller's drop (draft) -> ${r.s} ${r.j?.code}`); }
log("== 2. idempotency");
{ const key = "qa-fe5-" + crypto.randomBytes(6).toString("hex"); const em = `idem-${crypto.randomBytes(2).toString("hex")}@example.test`;
  const a = await co({ email: em }, { "idempotency-key": key }); const c2 = await co({ email: em }, { "idempotency-key": key }); const c3 = await co({ email: em }, { "idempotency-key": key });
  ok(a.s === 201 && c2.s === 200 && c3.s === 200 && a.j.transactionId === c2.j.transactionId && a.j.checkoutUrl === c2.j.checkoutUrl && c2.j.reused === true, `same key replay: ${a.s}/${c2.s}/${c3.s}, same transaction ${a.j.transactionId}, reused=${c2.j.reused}`);
  const par = await Promise.all(Array.from({ length: 10 }, () => co({ email: `par-${key}@example.test` }, { "idempotency-key": key + "-par" }))); const ids = new Set(par.map((r) => r.j?.transactionId)); ok(ids.size === 1 && par.every((r) => r.s === 200 || r.s === 201), `10 parallel same key -> ${ids.size} transaction(s): statuses ${par.map((r) => r.s).join(",")}`);
  const n = Number((await db.query("select count(*) from transactions where idempotency_key = $1 or idempotency_key=$2", [key, key + "-par"])).rows[0].count); ok(n === 2, `DB rows for the 2 keys = ${n}`);
  const other = await co({ email: em }, { "idempotency-key": key + "-other" }); ok(other.j?.transactionId !== a.j.transactionId, `different key + same cookie-less client -> new session (${other.s})`);
  const diffAmt = await co({ email: "different-" + em }, { "idempotency-key": key }); log(`   same key, different email -> ${diffAmt.s} tx ${diffAmt.j?.transactionId === a.j.transactionId ? "SAME tx (replay)" : "different"}`);
  const longKey = await co({}, { "idempotency-key": "k".repeat(300) }); log("   300-char key ->", longKey.s); ok(longKey.s < 500, "oversize idempotency key not 5xx");
  const badKey = await co({}, { "idempotency-key": "bad key with spaces \t" }); log("   key with spaces ->", badKey.s); ok(badKey.s < 500, "odd idempotency key not 5xx");
  // cross-client: someone else's key must not return my checkoutUrl
  const x = await co({ email: em }, { "idempotency-key": key + "-other" }); log(`   key reuse by 'another' client (same cookie-less) -> ${x.s}`);
  // paid then replay
  const k2 = "qa-fe5-paid-" + crypto.randomBytes(4).toString("hex"); const em2 = `paid-${crypto.randomBytes(2).toString("hex")}@example.test`; const p1 = await co({ email: em2 }, { "idempotency-key": k2 }); p1.email = em2; const sess = p1.j.checkoutUrl.split("/").pop(); const pay = await post("/api/dev/payments/pay", { sessionId: sess, card: "4242424242424242" }); ok(pay.j.status === "succeeded", "paid via mock"); const p2 = await co({ email: p1.email }, { "idempotency-key": k2 }); ok(p2.j?.transactionId === p1.j.transactionId && p2.j.status === "succeeded", `replay after payment returns the same succeeded transaction (${p2.s} ${p2.j?.status})`); const c = Number((await db.query("select count(*) from ledger_entries where transaction_id=$1 and entry_type='sale_credit'", [p1.j.transactionId])).rows[0].count); ok(c === 1, "exactly one sale_credit"); }
log("== 3. UI: validation, double click, redirect, pay, unlock");
async function ui(vp, tag) {
  const c = await b.newContext({ viewport: vp, extraHTTPHeaders: { "x-forwarded-for": L.fakeIp(45) } }); const p = await c.newPage(); const reqs = []; p.on("request", (r) => { if (r.url().includes("/api/checkout") && r.method() === "POST") reqs.push({ k: r.headers()["idempotency-key"], body: r.postData() }); });
  await p.goto(`${BASE}/u/${link}`); await p.waitForSelector("[data-testid=buy-form]");
  await p.locator("[data-testid=buy-button]").click(); await p.waitForTimeout(300); const errs0 = (await p.locator("[role=alert]").allInnerTexts()).join(" | "); ok(reqs.length === 0 && /valid email/i.test(await p.locator("main").innerText()) && /confirm/i.test(errs0), `[${tag}] empty submit -> no request, errors: ${errs0.replace(/\n/g, " ")} + email error`);
  await p.fill("#buyer-email", "not-an-email"); await p.locator("#over18").check(); await p.locator("[data-testid=buy-button]").click(); await p.waitForTimeout(300); ok(reqs.length === 0, `[${tag}] bad email blocked client-side`);
  await p.fill("#buyer-email", "ui-buyer@example.test"); await p.locator("#over18").uncheck(); await p.locator("[data-testid=buy-button]").click(); await p.waitForTimeout(300); ok(reqs.length === 0, `[${tag}] unchecked 18+ blocked client-side`);
  if (tag === "desktop") { await p.screenshot({ path: `${L.OUT}/fe5-buy-validation-desktop.png`, fullPage: true }); }
  await p.locator("#over18").check(); const btn = p.locator("[data-testid=buy-button]");
  const nav = p.waitForURL("**/pay/mock/**", { timeout: 15000 }); await btn.dblclick(); await btn.click({ force: true, noWaitAfter: true }).catch(() => {}); await nav;
  ok(/\/pay\/mock\/mocksess_/.test(p.url()), `[${tag}] redirected to hosted page ${p.url().replace(BASE, "")}`); ok(reqs.length >= 1 && new Set(reqs.map((r) => r.k)).size === 1 && /^[0-9a-f-]{36}$/.test(reqs[0].k), `[${tag}] ${reqs.length} POST(s) sent for the double-click, all with ONE Idempotency-Key ${reqs[0]?.k}`); ok(!/amount|price/i.test(reqs[0].body), `[${tag}] request body has no price field: ${reqs[0].body}`);
  const sess = p.url().split("/").pop(); const txs = (await db.query("select id,status,amount_cents,buyer_email,buyer_confirmed_18_at from transactions where provider_session_id=$1", [sess])).rows; ok(txs.length === 1 && txs[0].status === "pending" && txs[0].amount_cents === 2500 && txs[0].buyer_confirmed_18_at, `[${tag}] 1 pending tx $25.00 with 18+ timestamp`); const n2 = Number((await db.query("select count(*) from transactions where buyer_email='ui-buyer@example.test' and status='pending'")).rows[0].count); log(`   [${tag}] pending rows for ui-buyer: ${n2} (cumulative across runs)`);
  const txt = await p.locator("body").innerText(); ok(/\$25\.00/.test(txt) && /Studio colour study/.test(txt) && /sales are final|final/i.test(txt), `[${tag}] hosted page shows title, $25.00, final-sale text`); if (tag === "desktop") await p.screenshot({ path: `${L.OUT}/fe5-hosted-page.png`, fullPage: true });
  // back to the drop: still pending, nothing unlocked
  const html0 = await (await fetch(`${BASE}/u/${link}`)).text(); ok(!/href="[^"]*(\/original|\/download|signed|sig=)/i.test(html0) && !/storage_key|originals\//.test(html0), `[${tag}] public page before payment has no download/original hrefs (marketing copy 'Instant download' exists: ${/Instant download/.test(html0)})`);
  const st0 = await (await fetch(`${BASE}/api/checkout/status?id=${txs[0].id}`)).json(); ok(st0.status === "pending", `[${tag}] status endpoint pending: ${JSON.stringify(st0)}`);
  // declined card first
  await p.fill("#card", "4000 0000 0000 0002"); await p.locator("button:has-text('Pay (mock)')").click(); await p.waitForSelector("[data-testid=mock-result]"); const dmsg = await p.locator("[data-testid=mock-result]").innerText(); ok(!/card_declined|unrecognized|invalid_card|failure/i.test(dmsg), `[${tag}] declined card shows friendly text only: '${dmsg}'`);
  await p.fill("#card", "4242 4242 4242 4242"); await p.locator("button:has-text('Pay (mock)')").click(); await p.waitForFunction(() => /succeeded/i.test(document.querySelector("[data-testid=mock-result]")?.textContent ?? ""), null, { timeout: 10000 });
  const t1 = (await db.query("select status, seller_net_cents, platform_fee_cents, processing_fee_cents, amount_cents from transactions where id=$1", [txs[0].id])).rows[0]; ok(t1.status === "succeeded" && t1.amount_cents - t1.platform_fee_cents - t1.processing_fee_cents === t1.seller_net_cents, `[${tag}] webhook-driven: tx succeeded, split ${t1.amount_cents}-${t1.platform_fee_cents}-${t1.processing_fee_cents}=${t1.seller_net_cents}`);
  const led = (await db.query("select entry_type, component, amount_cents, available_at > now() as pend from ledger_entries where transaction_id=$1 order by id", [txs[0].id])).rows; log(`   [${tag}] ledger: ${JSON.stringify(led)}`); ok(led.length === 3 && led.every((l) => l.pend) && led.reduce((s, l) => s + l.amount_cents, 0) === t1.seller_net_cents, `[${tag}] 3 ledger lines, all pending (7-day hold), sum = seller net`);
  const st1 = await (await fetch(`${BASE}/api/checkout/status?id=${txs[0].id}`)).json(); ok(st1.status === "succeeded", `[${tag}] status endpoint succeeded: ${JSON.stringify(st1)}`);
  const tail = await p.locator("body").innerText(); log(`   [${tag}] after payment page text: ${tail.replace(/\n+/g, " | ").slice(0, 300)}`); if (tag === "desktop") await p.screenshot({ path: `${L.OUT}/fe5-hosted-paid.png`, fullPage: true });
  await p.goto(`${BASE}/u/${link}`); const html = await p.content(); const dl = await p.locator("a[href*='/original'], a[download], [data-testid*=download]").count(); log(`   [${tag}] after purchase, drop page: download links=${dl}; text mentions receipt/download: ${/receipt|your files|download now/i.test(await p.locator("main").innerText())}`);
  await c.close(); return { txId: txs[0].id, sess, html };
}
const D = await ui({ width: 1280, height: 900 }, "desktop"); await ui({ width: 390, height: 844 }, "mobile-390");
log("== 4. unlock / receipt / download availability (M2-14..16, M3-12/13)");
{ for (const path of [`/api/checkout/status?id=${D.txId}`, `/receipt/${D.txId}`, `/orders/${D.txId}`, `/download/${D.txId}`, `/api/receipts/${D.txId}`, `/api/orders/${D.txId}`, `/api/downloads/${D.txId}`, `/u/${link}/download`, `/api/checkout/${D.txId}`]) { const r = await fetch(BASE + path, { redirect: "manual" }); log(`   GET ${path.replace(D.txId, "<tx>")} -> ${r.status}`); }
  const files = (await db.query("select id from drop_files where drop_id=$1 limit 1", [dropId])).rows[0]; const r = await fetch(`${BASE}/api/files/${files.id}/original`); ok(r.status === 403 || r.status === 401 || r.status === 404, `buyer (paid, no signed URL) direct original -> ${r.status} (no purchase-bound download exists)`);
  const fs = await import("node:fs"); const md = process.env.MAIL_DIR ?? "/workspace/qa-fe5/.qa-mail"; const mails = fs.existsSync(md) ? fs.readdirSync(md).length : 0; log(`   mail files in dev mail dir after purchases: ${mails} (receipt email = none expected)`); }
L.done(); await b.close(); await db.end();
