// @ts-nocheck
/* eslint-disable */
// Round 3 QA, item 3: admin foundation (auth, isolation, CSRF, XSS, IDOR, audit, CLI) + (d) chargeback re-flag after clear.
process.env.MOCK_PAYMENTS_ENABLED ??= "1";
import { execFileSync, spawnSync } from "node:child_process";
import crypto from "node:crypto";
import { SignJWT } from "jose";
import { Http, BASE, check, assert, eq, db, makeSeller, makeDrop, txRow, save, done, sell, sendWebhook, paySale, cbEv, refundEv, stamp, ledgerCount, sleep } from "./qa-pay5-lib";

const B2 = "http://localhost:3918"; const PW = "Qa-Admin-Passphrase-93!x"; const SESSION_SECRET = process.env.SESSION_SECRET!;
const n = async (sql: string, p: unknown[] = []) => Number((await db.query(sql, p)).rows[0].n);
function cli(args: string[], env: Record<string, string> = {}) {
  const e: any = { ...process.env, ...env }; if (!("ADMIN_PASSWORD" in env)) delete e.ADMIN_PASSWORD;
  const r = spawnSync("npx", ["tsx", "scripts/create-admin.ts", ...args], { env: e, encoding: "utf8", input: "" }); return { code: r.status, out: (r.stdout ?? "") + (r.stderr ?? "") };
}
const mkAdmin = (label: string) => { const email = `adm-${label}-${stamp}@example.test`; const r = cli([email], { ADMIN_PASSWORD: PW }); if (r.code !== 0) throw new Error("create-admin " + r.out); return email; };
const login = async (email: string, pw = PW, http = new Http(), base = BASE) => { const r = await http.json("POST", "/api/admin/login", { json: { email, password: pw }, base }); return { http, r }; };
const adminCookieOf = (h: Http) => h.cookies.get("unveil_admin");
const getp = (h: Http, path: string, base = BASE, headers: Record<string, string> = {}) => h.req("GET", path, { base, headers });
const derivedKey = () => crypto.createHash("sha256").update(`unveil-admin-session:${SESSION_SECRET}`).digest();
const rawKey = () => new TextEncoder().encode(SESSION_SECRET);
const ADMIN_API: [string, string][] = [["GET", "/api/admin/me"], ["GET", "/api/admin/sellers/flagged"], ["GET", "/api/admin/transactions/review"], ["POST", "/api/admin/sellers/00000000-0000-0000-0000-000000000000/clear-flag"]];
const ADMIN_PAGES = ["/admin", "/admin/sellers/flagged", "/admin/sellers/00000000-0000-0000-0000-000000000000/transactions"];

(async () => {
  const seller = await makeSeller("n3"); const d = await makeDrop(seller, 2000);
  const adminEmail = mkAdmin("a"); const { http: A } = await login(adminEmail);

  // ----------------- CLI -----------------
  await check("ADM-CLI-1", "create-admin CLI: creates admin (lowercases email, bcrypt hash, audit admin_created_cli), duplicate rejected, --reset-password rotates + revokes sessions, password never printed/in argv/audit", async () => {
    const email = `Adm-Cli-${stamp}@Example.Test`; const r1 = cli([email], { ADMIN_PASSWORD: PW }); eq(r1.code, 0, r1.out); assert(!r1.out.includes(PW), "password echoed"); const row = (await db.query("SELECT email,password_hash FROM admins WHERE email=$1", [email.toLowerCase()])).rows[0]; assert(row, "row"); assert(/^\$2[aby]\$/.test(row.password_hash), "bcrypt");
    const dup = cli([email], { ADMIN_PASSWORD: PW }); assert(dup.code !== 0 && /already exists/.test(dup.out), "dup " + dup.out); const l1 = await login(email.toLowerCase()); eq(l1.r.status, 200, "login");
    const rs = cli([email, "--reset-password"], { ADMIN_PASSWORD: "Another-Strong-Pass-77#z" }); eq(rs.code, 0, rs.out); const stale = await l1.http.json("GET", "/api/admin/me"); eq(stale.status, 401, "old session after reset"); const old = await login(email, PW); eq(old.r.status, 401, "old pw"); const nw = await login(email, "Another-Strong-Pass-77#z"); eq(nw.r.status, 200, "new pw");
    const aud = await db.query("SELECT action FROM audit_log WHERE target LIKE $1 ORDER BY created_at", [`admin:${row.id ?? ""}%`]); const acts = (await db.query("SELECT action, target FROM audit_log WHERE action LIKE 'admin_%' AND target LIKE '%'||(SELECT id::text FROM admins WHERE email=$1)||'%' ORDER BY created_at", [email.toLowerCase()])).rows.map((x) => x.action);
    assert(acts.includes("admin_created_cli") && acts.includes("admin_password_reset_cli"), "audit " + acts); assert(!(await db.query("SELECT 1 FROM audit_log WHERE target LIKE '%'||$1||'%'", [PW])).rowCount, "pw in audit");
    return `created (email lowercased, bcrypt), duplicate → exit≠0 'already exists', reset revokes old session (401) & old pw 401 & new pw 200; audit: ${acts.join(",")}`;
  });
  await check("ADM-CLI-2", "CLI input validation: bad emails, weak/short/common/sequential/long passwords, password-as-argv flags, no TTY & no ADMIN_PASSWORD, extra args", async () => {
    const out: string[] = []; const bad = ["", "not-an-email", "a@b", "@x.com", "a b@x.com", "x".repeat(260) + "@example.test"]; for (const e of bad) { const r = cli(e ? [e] : [], { ADMIN_PASSWORD: PW }); assert(r.code !== 0, `email ${JSON.stringify(e).slice(0, 20)} accepted`); }
    const e0 = `adm-pw-${stamp}@example.test`; for (const [name, p] of [["short", "Ab1!xyz"], ["password", "password123456"], ["seq", "1234567890"], ["repeat", "aaaaaaaaaaaa"], ["email-in-pw", e0], ["201 chars", "Aa1!".repeat(51)]] as const) { const r = cli([e0], { ADMIN_PASSWORD: p }); assert(r.code !== 0, `weak password accepted: ${name}`); }
    assert((await n("SELECT count(*) n FROM admins WHERE email=$1", [e0])) === 0, "weak admin created");
    const argvPw = cli([e0, "--password", PW], { ADMIN_PASSWORD: PW }); assert(argvPw.code === 2, "argv password flag should be refused (usage exit 2): " + argvPw.code); const argvPw2 = cli([e0, `--password=${PW}`]); assert(argvPw2.code !== 0, "--password= accepted");
    const noTty = cli([e0]); assert(noTty.code !== 0 && /TTY|ADMIN_PASSWORD/.test(noTty.out), "no tty → " + noTty.out); const ok = cli([e0], { ADMIN_PASSWORD: PW }); eq(ok.code, 0, ok.out);
    return `6 bad emails, 6 weak passwords rejected (nothing created); argv password flag refused (exit 2); no TTY → refuses; valid creates`;
  });

  // ----------------- anonymous / seller isolation -----------------
  await check("ADM-AUTHZ-1", "anonymous: every /api/admin route (GET/POST/PUT/DELETE/PATCH/HEAD variants) → 401 (never 200/500), body leaks nothing; pages redirect to /admin/login without data", async () => {
    const out: string[] = []; const anon = new Http();
    for (const [m, p] of ADMIN_API) { const r = await anon.json(m, p, m === "POST" ? { json: { note: "anon attempt" } } : {}); eq(r.status, 401, `${m} ${p}: ${r.status} ${r.text.slice(0, 80)}`); assert(!/password|\$2b|@example/.test(r.text), "leak"); out.push(`${m}:${r.status}`); }
    for (const m of ["PUT", "DELETE", "PATCH"]) for (const [, p] of ADMIN_API.slice(1, 3)) { const r = await anon.json(m, p); assert([401, 405].includes(r.status), `${m} ${p} ${r.status}`); }
    for (const p of ADMIN_PAGES) { const r = await getp(anon, p); assert([302, 303, 307, 308].includes(r.status), `${p}: ${r.status}`); assert((r.headers.get("location") ?? "").includes("/admin/login"), "redirect target " + r.headers.get("location")); const t = await r.text(); assert(!/Flagged sellers|Transactions needing review/.test(t), "page data leaked"); out.push(`${p.slice(0, 22)}:${r.status}`); }
    const login = await getp(anon, "/admin/login"); eq(login.status, 200, "login page"); const unknown = await (await getp(anon, "/api/admin/nonexistent")).status; return out.join(" ") + `; /api/admin/nonexistent → ${unknown}`;
  });
  await check("ADM-AUTHZ-2", "seller session → admin routes: 403 (never data); seller token pasted into unveil_admin cookie → 401; admin cookie on seller routes (/api/earnings, /api/drops, /api/auth/*) → 401; both cookies at once resolve separately", async () => {
    const out: string[] = []; for (const [m, p] of ADMIN_API) { const r = await seller.http.json(m, p, m === "POST" ? { json: { note: "seller attempt" } } : {}); eq(r.status, 403, `seller ${m} ${p}: ${r.status}`); out.push(`${r.status}`); }
    const sellerTok = seller.http.cookies.get("unveil_session"); assert(sellerTok, "seller cookie"); const x = new Http(); x.cookies.set("unveil_admin", sellerTok); for (const [m, p] of ADMIN_API.slice(0, 3)) eq((await x.json(m, p)).status, 401, `seller token as admin cookie ${p}`);
    const pg = await getp(x, "/admin/sellers/flagged"); assert([302, 303, 307].includes(pg.status), "page with seller token as admin cookie " + pg.status);
    const y = new Http(); y.cookies.set("unveil_session", adminCookieOf(A)); for (const p of ["/api/earnings", "/api/drops", "/api/auth/me"]) { const r = await y.json("GET", p); assert(r.status === 401 || r.status === 404, `admin token as seller cookie ${p}: ${r.status}`); }
    const both = new Http(); both.cookies.set("unveil_admin", adminCookieOf(A)); both.cookies.set("unveil_session", seller.http.cookies.get("unveil_session")); eq((await both.json("GET", "/api/admin/me")).status, 200, "both: admin"); eq((await both.json("GET", "/api/earnings")).status, 200, "both: seller");
    return `seller → 4 admin routes all 403; seller token in admin cookie → 401; admin token in seller cookie → 401/404; both cookies resolve per-principal`;
  });
  await check("ADM-AUTHZ-3", "forged admin tokens: alg=none, HS256 w/ raw SESSION_SECRET (seller key) + admin aud, derived key but wrong aud, derived key + unknown jti, derived key + expired, tampered signature, jti of a REVOKED session, garbage → all 401", async () => {
    const adm = (await db.query("SELECT id FROM admins WHERE email=$1", [adminEmail])).rows[0].id; const live = (await db.query("SELECT id FROM admin_sessions WHERE admin_id=$1 AND revoked_at IS NULL LIMIT 1", [adm])).rows[0].id;
    const mk = (key: any, o: { aud?: string; jti?: string; sub?: string; exp?: string; alg?: string } = {}) => new SignJWT({}).setProtectedHeader({ alg: o.alg ?? "HS256" }).setSubject(o.sub ?? adm).setAudience(o.aud ?? "unveil-admin").setJti(o.jti ?? live).setIssuedAt().setExpirationTime(o.exp ?? "1h").sign(key);
    const tampered = (await mk(derivedKey())).replace(/.$/, (c) => (c === "A" ? "B" : "A")); const none = Buffer.from(JSON.stringify({ alg: "none", typ: "JWT" })).toString("base64url") + "." + Buffer.from(JSON.stringify({ sub: adm, aud: "unveil-admin", jti: live, exp: Math.floor(Date.now() / 1000) + 3600 })).toString("base64url") + ".";
    const revoked = (await login(adminEmail)); const revId = (await db.query("SELECT id FROM admin_sessions WHERE admin_id=$1 ORDER BY created_at DESC LIMIT 1", [adm])).rows[0].id; await revoked.http.json("POST", "/api/admin/logout");
    const sellerLike = await new SignJWT({ sub: seller.id }).setProtectedHeader({ alg: "HS256" }).setSubject(seller.id).setIssuedAt().setExpirationTime("1h").sign(rawKey());
    const toks: Record<string, string> = { alg_none: none, raw_secret_admin_aud: await mk(rawKey()), derived_wrong_aud: await mk(derivedKey(), { aud: "unveil" }), derived_unknown_jti: await mk(derivedKey(), { jti: crypto.randomUUID() }), derived_nonuuid_jti: await mk(derivedKey(), { jti: "x" }), derived_expired: await mk(derivedKey(), { exp: "-10s" }), tampered, revoked_session: await mk(derivedKey(), { jti: revId }), seller_token: sellerLike, garbage: "abc.def.ghi", empty: "", sub_other_admin: await mk(derivedKey(), { sub: crypto.randomUUID() }) };
    const out: string[] = []; for (const [k, t] of Object.entries(toks)) { const x = new Http(); if (t) x.cookies.set("unveil_admin", t); const r = await x.json("GET", "/api/admin/me"); assert(r.status === 401 || r.status === 403, `${k}: ${r.status} ${r.text.slice(0, 80)}`); out.push(`${k}:${r.status}`); }
    const ctl = new Http(); ctl.cookies.set("unveil_admin", await mk(derivedKey())); const okc = await ctl.json("GET", "/api/admin/me"); eq(okc.status, 200, "control: correctly forged-with-derived-key but REAL session id is accepted (expected: QA holds SESSION_SECRET)");
    return out.join(" ") + " | control (QA knows secret + real jti) 200";
  });
  await check("ADM-SESS-1", "session lifecycle: new session per login (fixation: pre-login cookie ignored/replaced), logout revokes server-side (old cookie 401 even if replayed), expiry enforced via DB, 8h Max-Age, two sessions independent, logout idempotent", async () => {
    const pre = new Http(); pre.cookies.set("unveil_admin", "attacker-chosen-value"); const l = await login(adminEmail, PW, pre); eq(l.r.status, 200, "login"); const tok = adminCookieOf(pre); assert(tok && tok !== "attacker-chosen-value", "fixed cookie kept");
    const l2 = await login(adminEmail); assert(adminCookieOf(l2.http) !== tok, "same token twice"); const sc = l.r.headers.get("set-cookie") ?? ""; assert(/Max-Age=28800/i.test(sc), "max-age " + sc);
    const replay = new Http(); replay.cookies.set("unveil_admin", tok); eq((await replay.json("GET", "/api/admin/me")).status, 200, "before logout"); await pre.json("POST", "/api/admin/logout"); eq((await replay.json("GET", "/api/admin/me")).status, 401, "replayed cookie after logout"); eq((await l2.http.json("GET", "/api/admin/me")).status, 200, "other session still valid");
    const lo2 = await replay.json("POST", "/api/admin/logout"); assert(lo2.status < 500, "logout twice " + lo2.status); const anonLogout = await new Http().json("POST", "/api/admin/logout"); assert(anonLogout.status < 500, "anon logout " + anonLogout.status);
    const sid = (await db.query("SELECT id FROM admin_sessions WHERE admin_id=(SELECT id FROM admins WHERE email=$1) AND revoked_at IS NULL ORDER BY created_at DESC LIMIT 1", [adminEmail])).rows[0].id; await db.query("UPDATE admin_sessions SET expires_at = now() - interval '1 second' WHERE id=$1", [sid]); eq((await l2.http.json("GET", "/api/admin/me")).status, 401, "expired session");
    return `fresh token per login; attacker-chosen cookie replaced; logout → replay 401 (server-side), other session unaffected; expires_at in past → 401; Max-Age=28800; logout twice/anonymous → ${lo2.status}/${anonLogout.status}`;
  });
  await check("ADM-SESS-2", "disabled admin: existing session stops working IMMEDIATELY (same second), login refused with uniform 401, re-enable restores login; deleting admin cascades sessions", async () => {
    const email = mkAdmin("dis"); const s1 = await login(email); const s2 = await login(email); eq((await s1.http.json("GET", "/api/admin/sellers/flagged")).status, 200, "pre");
    await db.query("UPDATE admins SET disabled_at=now() WHERE email=$1", [email]); const t0 = Date.now(); const r1 = await s1.http.json("GET", "/api/admin/me"); const r2 = await s2.http.json("GET", "/api/admin/sellers/flagged"); const pg = await getp(s1.http, "/admin/sellers/flagged");
    eq(r1.status, 401, "me after disable"); eq(r2.status, 401, "flagged after disable"); assert([302, 303, 307].includes(pg.status), "page after disable " + pg.status); const nl = await login(email); eq(nl.r.status, 401, "login disabled"); eq(nl.r.json.code, "invalid_credentials", "uniform code");
    await db.query("UPDATE admins SET disabled_at=NULL WHERE email=$1", [email]); eq((await login(email)).r.status, 200, "re-enabled"); const idv = (await db.query("SELECT id FROM admins WHERE email=$1", [email])).rows[0].id; let delErr = ""; await db.query("DELETE FROM admins WHERE id=$1", [idv]).catch((e) => { delErr = e.message; }); /* R4 (declared change, migration 011): an admin with audit history can no longer be deleted */ assert(/audit history and cannot be deleted/.test(delErr), "delete should be refused: " + delErr); eq(await n("SELECT count(*) n FROM admins WHERE id=$1", [idv]), 1, "admin kept");
    return `disable → both live sessions 401 within ${Date.now() - t0} ms of the UPDATE; disabled login 401 invalid_credentials; re-enable works; R4: DELETE of an admin with audit history is refused (was: cascade)`;
  });

  // ----------------- login -----------------
  await check("ADM-LOGIN-1", "login: uniform 401 body/code for unknown email, wrong password, disabled; malformed bodies 400 (not 500); response never includes hash; case-insensitive email; no cookie set on failure", async () => {
    const dis = mkAdmin("dis2"); await db.query("UPDATE admins SET disabled_at=now() WHERE email=$1", [dis]);
    const rs = [await login("nobody-" + stamp + "@example.test", PW), await login(adminEmail, "wrong-password-123"), await login(dis, PW)]; const bodies = new Set(rs.map((x) => x.r.text)); eq(bodies.size, 1, "bodies differ: " + [...bodies]); for (const x of rs) { eq(x.r.status, 401, "status"); assert(!x.r.headers.get("set-cookie"), "cookie on failure"); }
    const bad: [string, any][] = [["no body", undefined], ["array", []], ["missing pw", { email: adminEmail }], ["pw number", { email: adminEmail, password: 123 }], ["huge pw", { email: adminEmail, password: "a".repeat(100000) }], ["email NUL", { email: "a\u0000@x.com", password: "x" }], ["pw NUL", { email: adminEmail, password: "x\u0000y" }], ["sqli", { email: "' OR 1=1--@x.com", password: "' OR '1'='1" }], ["email obj", { email: { $ne: 1 }, password: "x" }], ["unicode", { email: "ü@x.com", password: "\ud800" }]];
    const st: string[] = []; for (const [nm, b] of bad) { const r = await new Http().json("POST", "/api/admin/login", b === undefined ? { raw: "" } : { json: b }); assert(r.status >= 400 && r.status < 500, `${nm}: ${r.status} ${r.text.slice(0, 100)}`); st.push(`${nm}:${r.status}`); }
    const up = await login(adminEmail.toUpperCase()); eq(up.r.status, 200, "case-insens"); assert(!JSON.stringify(up.r.json).includes("$2"), "hash"); return `uniform 401 body "${[...bodies][0]}" for unknown/wrong/disabled; no Set-Cookie; ${st.join(" ")}; uppercase email logs in`;
  });
  await check("ADM-LOGIN-2", "per-email progressive delay (namespaced 'admin:<email>'): 20 wrong passwords → 429+Retry-After; correct password DURING delay refused; delay on admin address doesn't delay a SELLER with the same email, and seller spam doesn't delay admin", async () => {
    const email = `shared-${stamp}@example.test`; cli([email], { ADMIN_PASSWORD: PW }); const sp = new Http(); const su = await sp.json("POST", "/api/auth/signup", { json: { email, password: "Qa-Pay-Passw0rd!x", displayName: "Shared" } }); eq(su.status, 201, "seller signup");
    const codes: number[] = []; let ra = 0; for (let i = 0; i < 12; i++) { const r = await new Http().json("POST", "/api/admin/login", { json: { email, password: "wrong-pass-" + i } }); codes.push(r.status); if (r.status === 429) ra = Number(r.headers.get("retry-after")); }
    assert(codes.includes(429), "never delayed: " + codes); assert(ra >= 1, "Retry-After"); const during = await login(email, PW); eq(during.r.status, 429, "correct password during delay"); const seller = await new Http().json("POST", "/api/auth/login", { json: { email, password: "Qa-Pay-Passw0rd!x" } }); eq(seller.status, 200, "seller login unaffected by admin delay");
    const email2 = `shared2-${stamp}@example.test`; cli([email2], { ADMIN_PASSWORD: PW }); await new Http().json("POST", "/api/auth/signup", { json: { email: email2, password: "Qa-Pay-Passw0rd!x", displayName: "Shared2" } }); const sc: number[] = []; for (let i = 0; i < 12; i++) sc.push((await new Http().json("POST", "/api/auth/login", { json: { email: email2, password: "wrong-pass-" + i } })).status); assert(sc.includes(429), "seller delay not applied " + sc); const adm = await login(email2, PW); eq(adm.r.status, 200, "admin login unaffected by seller delay");
    return `admin: ${codes.join(",")} (Retry-After ${ra}); correct pw during delay → 429; seller login with same email → 200; seller spam (${sc.filter((x) => x === 429).length}×429) leaves admin login 200`;
  });
  await check("ADM-LOGIN-3", "per-IP limiter on default-limits server (10 / 15 min): 10 attempts then 429 even for valid creds; other IP unaffected; spoofed rotating XFF evades (same deployment note as M3-16)", async () => {
    const ipx = `10.230.${Math.floor(Math.random() * 250)}.${Math.floor(Math.random() * 250)}`; const codes: number[] = []; for (let i = 0; i < 13; i++) { const h = new Http(); h.ip = ipx; codes.push((await h.json("POST", "/api/admin/login", { base: B2, json: { email: `noone${i}-${stamp}@example.test`, password: "x-wrong-pass" } })).status); }
    const h = new Http(); h.ip = ipx; const good = await h.json("POST", "/api/admin/login", { base: B2, json: { email: adminEmail, password: PW } }); const other = new Http(); const ok = await other.json("POST", "/api/admin/login", { base: B2, json: { email: adminEmail, password: PW } });
    const first429 = codes.indexOf(429); assert(first429 >= 9 && first429 <= 11, "first 429 at " + first429 + " " + codes); eq(good.status, 429, "valid creds while IP limited"); eq(ok.status, 200, "other ip"); let ev = 0; for (let i = 0; i < 25; i++) { const x = new Http(); const r = await x.json("POST", "/api/admin/login", { base: B2, json: { email: `ev${i}-${stamp}@example.test`, password: "x-wrong-pass" } }); if (r.status === 401) ev++; }
    return `first 429 at attempt #${first429 + 1}; valid creds from limited IP → 429; other IP → 200; 25 attempts each with fresh XFF → ${ev}×401 (no cap: deployment must overwrite XFF)`;
  });
  await check("ADM-LOGIN-4", "enumeration via timing: median latency of unknown-email vs known-email wrong-password (bcrypt on both?)", async () => {
    const tAdmin = mkAdmin("timing"); const med = (a: number[]) => a.sort((x, y) => x - y)[Math.floor(a.length / 2)]; const t1: number[] = [], t2: number[] = [];
    for (let i = 0; i < 10; i++) { let t = Date.now(); await new Http().json("POST", "/api/admin/login", { json: { email: `ghost${i}-${stamp}@example.test`, password: "Wrong-Pass-123!" } }); t1.push(Date.now() - t); t = Date.now(); await new Http().json("POST", "/api/admin/login", { json: { email: tAdmin, password: "Wrong-Pass-123!" } }); t2.push(Date.now() - t); }
    const m1 = med(t1), m2 = med(t2); assert(Math.abs(m1 - m2) < Math.max(40, m2 * 0.5), `timing gap ${m1} vs ${m2}`); return `median unknown-email ${m1} ms vs known-email wrong pw ${m2} ms (first 4 wrong guesses are un-delayed; both bcrypt-bound; no enumeration signal)`;
  });
  await check("ADM-COOKIE-1", "admin cookie flags: HttpOnly, SameSite=Strict, Secure (prod build), Path=/, Max-Age 28800, no Domain; Cache-Control: no-store on API/pages; logout cookie cleared (Max-Age=0)", async () => {
    const cAdmin = mkAdmin("cookie"); const x = new Http(); const r = await x.json("POST", "/api/admin/login", { json: { email: cAdmin, password: PW } }); assert(r.status === 200, "login " + r.status); const sc = r.headers.getSetCookie().join("\n"); for (const re of [/unveil_admin=/, /HttpOnly/i, /SameSite=strict/i, /Secure/i, /Path=\/(;|$)/i, /Max-Age=28800/i]) assert(re.test(sc), `missing ${re}: ${sc.replace(/=[^;]{20,}/, "=<tok>")}`); assert(!/Domain=/i.test(sc), "Domain");
    const lo = await x.json("POST", "/api/admin/logout"); const sc2 = lo.headers.getSetCookie().join("\n"); assert(/Max-Age=0/i.test(sc2) || /Expires=Thu, 01 Jan 1970/i.test(sc2), "logout not cleared " + sc2); return sc.replace(/=[^;]{20,}/, "=<tok>") + " | logout: " + sc2.replace(/=[^;]{20,}/, "=<tok>").slice(0, 120);
  });
  await check("ADM-NOINDEX-1", "admin pages/APIs: X-Robots-Tag noindex, <meta robots noindex>, Cache-Control no-store, robots.txt Disallow:/admin; not linked from public pages (home, /u/<link>, sitemap)", async () => {
    const out: string[] = []; const login = await getp(new Http(), "/admin/login"); const lt = await login.text(); assert(/noindex/i.test(login.headers.get("x-robots-tag") ?? ""), "login X-Robots-Tag"); assert(/<meta name="robots" content="[^"]*noindex/i.test(lt), "meta robots on login"); assert(/no-store/i.test(login.headers.get("cache-control") ?? ""), "login cache-control");
    const pg = await getp(A, "/admin/sellers/flagged"); const t = await pg.text(); eq(pg.status, 200, "flagged page"); assert(/noindex/i.test(pg.headers.get("x-robots-tag") ?? ""), "XRT"); assert(/<meta name="robots" content="[^"]*noindex/i.test(t), "meta"); assert(/no-store/i.test(pg.headers.get("cache-control") ?? ""), "cc");
    const api = await A.req("GET", "/api/admin/me"); assert(/noindex/i.test(api.headers.get("x-robots-tag") ?? "") && /no-store/i.test(api.headers.get("cache-control") ?? ""), "api headers"); const robots = await (await fetch(BASE + "/robots.txt")).text(); assert(/Disallow: \/admin/.test(robots), "robots " + robots);
    for (const p of ["/", `/u/${d.link}`, "/sitemap.xml"]) { const r = await fetch(BASE + p); if (r.status === 200) assert(!/\/admin/.test(await r.text()), `admin link on ${p}`); } return "login+flagged pages and APIs: noindex header (+meta), no-store; robots.txt Disallow:/admin; no /admin link on /, /u/<link>, sitemap";
  });

  // ----------------- CSRF -----------------
  const flagSeller = async (label: string, nCb = 3) => { const s2 = await makeSeller(label); const dd = await makeDrop(s2, 2000); const txs: string[] = []; for (let i = 0; i < nCb; i++) { const t = await sell(dd.link, 2000); txs.push(t); await sendWebhook(cbEv(t, null, 1)); } return { s2, dd, txs }; };
  await check("ADM-CSRF-1", "clear-flag & login CSRF: foreign Origin (evil.example, localhost.evil.com, null, scheme/port mismatch, garbage) → 403 and NO state change; text/plain content-type cross-site simple POST blocked by Origin check; missing Origin allowed (non-browser) but cookie is SameSite=Strict", async () => {
    const { s2 } = await flagSeller("csrf"); const ok = (await db.query("SELECT risk_flagged_at FROM sellers WHERE id=$1", [s2.id])).rows[0].risk_flagged_at; assert(ok, "not flagged");
    const origins = ["http://evil.example", "https://evil.example", "null", "http://localhost.evil.com", "http://localhost:3917.evil.com", "http://localhost:9999", "garbage", "http://evil.example/http://localhost:3917", "file://"]; const out: string[] = [];
    for (const o of origins) for (const ct of ["application/json", "text/plain", "application/x-www-form-urlencoded"]) { const x = new Http(); x.cookies = new Map(A.cookies); const r = await x.json("POST", `/api/admin/sellers/${s2.id}/clear-flag`, { raw: JSON.stringify({ note: "csrf attempt note" }), headers: { origin: o, "content-type": ct } }); if (r.status !== 403) out.push(`${o}/${ct}→${r.status}`); }
    assert(!out.length, "not blocked: " + out.join(", ")); const still = (await db.query("SELECT risk_flagged_at FROM sellers WHERE id=$1", [s2.id])).rows[0].risk_flagged_at; assert(still, "flag cleared by CSRF!");
    const lg = await new Http().json("POST", "/api/admin/login", { json: { email: adminEmail, password: PW }, headers: { origin: "http://evil.example" } }); eq(lg.status, 403, "login CSRF"); const lo = await A.json("POST", "/api/admin/logout", { headers: { origin: "http://evil.example" } }); eq(lo.status, 403, "logout CSRF"); eq((await A.json("GET", "/api/admin/me")).status, 200, "still logged in after blocked logout");
    const schemeOnly = new Http(); schemeOnly.cookies = new Map(A.cookies); const so = await schemeOnly.json("POST", `/api/admin/sellers/${s2.id}/clear-flag`, { raw: JSON.stringify({ note: "scheme only mismatch" }), headers: { origin: "https://localhost:3917", "content-type": "application/json" } }); const noOrigin = new Http(); noOrigin.cookies = new Map(A.cookies); const nr = await noOrigin.json("POST", `/api/admin/sellers/${s2.id}/clear-flag`, { raw: JSON.stringify({ note: "no origin header, text/plain" }), headers: { "content-type": "text/plain" } }); 
    return `${origins.length}×3 foreign-origin/content-type combos → 403, flag intact; login & logout CSRF 403; INFO-a: Origin check compares host only, not scheme: Origin https://localhost:3917 vs http app → ${so.status === 403 ? '403 blocked' : 'not blocked (' + so.status + ')'}; INFO-b: request WITHOUT Origin and with text/plain is accepted (${nr.status}) — only reachable by non-browser clients; browsers always send Origin on cross-site POST and the cookie is SameSite=Strict`;
  });

  // ----------------- clear-flag semantics / IDOR / injection -----------------
  let flagged: any;
  await check("ADM-FLAG-1", "flagged list shows seller (name,email,reason,counts), review list; clear-flag requires note 3-500 chars; double clear → 409 not_flagged; unknown id 404; bad id 404; SQLi/IDOR ids; mass-assignment fields ignored; audit row w/ admin id + timestamp", async () => {
    flagged = await flagSeller("flag1"); const { s2 } = flagged; const list = (await A.json("GET", "/api/admin/sellers/flagged")).json.sellers; const row = list.find((x) => x.id === s2.id); assert(row, "seller in list"); eq(row.chargebacks, 3, "cb count"); assert(row.flagReason, "reason"); const keys = Object.keys(row).sort().join();
    for (const note of ["", "  ", "ab", "x".repeat(501), "   a  "]) { const r = await A.json("POST", `/api/admin/sellers/${s2.id}/clear-flag`, { json: { note } }); eq(r.status, 400, `note ${JSON.stringify(note).slice(0, 12)}: ${r.status} ${r.text.slice(0, 80)}`); }
    for (const body of [{}, { note: 5 }, { note: ["abc"] }, { note: null }]) { const r = await A.json("POST", `/api/admin/sellers/${s2.id}/clear-flag`, { json: body }); eq(r.status, 400, "invalid body " + JSON.stringify(body)); } const rj = await A.json("POST", `/api/admin/sellers/${s2.id}/clear-flag`, { raw: "{not json" }); eq(rj.status, 400, "bad json");
    eq((await db.query("SELECT risk_flagged_at IS NOT NULL f FROM sellers WHERE id=$1", [s2.id])).rows[0].f, true, "still flagged after invalid attempts");
    for (const id of ["' OR 1=1--", "00000000-0000-0000-0000-000000000000", "../../etc/passwd", "%00", "1; DROP TABLE sellers;--", s2.id.toUpperCase().slice(0, 35) + "x", "a".repeat(5000)]) { const r = await A.json("POST", `/api/admin/sellers/${encodeURIComponent(id)}/clear-flag`, { json: { note: "probe note ok" } }); assert([404, 400].includes(r.status), `id ${id.slice(0, 20)}: ${r.status} ${r.text.slice(0, 80)}`); }
    const unflagged = await A.json("POST", `/api/admin/sellers/${seller.id}/clear-flag`, { json: { note: "not flagged seller" } }); eq(unflagged.status, 409, "unflagged"); eq(unflagged.json.code, "not_flagged", "code");
    const t0 = Date.now(); const ok = await A.json("POST", `/api/admin/sellers/${s2.id}/clear-flag`, { json: { note: "  Reviewed: legit refunds mix  ", risk_flagged_at: "2030-01-01", adminId: crypto.randomUUID(), sellerId: seller.id, risk_reviewed_by: crypto.randomUUID(), admin_id: crypto.randomUUID() } }); eq(ok.status, 200, ok.text);
    const sr = (await db.query("SELECT risk_flagged_at, risk_flag_reason, risk_reviewed_at, risk_reviewed_by, risk_review_note FROM sellers WHERE id=$1", [s2.id])).rows[0]; const adminId = (await db.query("SELECT id FROM admins WHERE email=$1", [adminEmail])).rows[0].id; eq(sr.risk_flagged_at, null, "cleared"); eq(sr.risk_reviewed_by, adminId, "reviewer = session admin (mass assignment ignored)"); eq(sr.risk_review_note, "Reviewed: legit refunds mix", "note trimmed");
    const aud = (await db.query("SELECT admin_id, action, target, created_at FROM audit_log WHERE action='seller_flag_cleared' AND target LIKE $1", [`seller:${s2.id}%`])).rows; eq(aud.length, 1, "audit rows"); eq(aud[0].admin_id, adminId, "audit admin"); assert(Math.abs(new Date(aud[0].created_at).getTime() - t0) < 10000, "audit time"); assert(/note: Reviewed: legit refunds mix/.test(aud[0].target) && /previous_reason/.test(aud[0].target), "audit target " + aud[0].target);
    const dbl = await A.json("POST", `/api/admin/sellers/${s2.id}/clear-flag`, { json: { note: "second clear attempt" } }); eq(dbl.status, 409, "double clear"); eq(await n("SELECT count(*) n FROM audit_log WHERE action='seller_flag_cleared' AND target LIKE $1", [`seller:${s2.id}%`]), 1, "audit rows after double");
    return `list row keys=[${keys}]; invalid notes/bodies/ids → 400/404, flag untouched; unflagged → 409; success 200 (reviewer = session admin despite body fields); 1 audit row (admin_id, created_at, previous_reason, note); double clear 409, still 1 audit row`;
  });
  await check("ADM-FLAG-2", "concurrent clear ×10 (and clear racing 3rd chargeback) → exactly one 200, rest 409, exactly one audit row; no 5xx/deadlock", async () => {
    const f = await flagSeller("flag2"); const rs = await Promise.all(Array.from({ length: 10 }, (_, i) => A.json("POST", `/api/admin/sellers/${f.s2.id}/clear-flag`, { json: { note: "concurrent clear " + i } }))); const st = rs.map((r) => r.status).sort(); eq(rs.filter((r) => r.status === 200).length, 1, "one 200 " + st); assert(rs.every((r) => [200, 409].includes(r.status)), "statuses " + st); eq(await n("SELECT count(*) n FROM audit_log WHERE action='seller_flag_cleared' AND target LIKE $1", [`seller:${f.s2.id}%`]), 1, "audit");
    const g = await makeSeller("flag3"); const gd = await makeDrop(g, 2000); const t1 = await sell(gd.link, 2000), t2 = await sell(gd.link, 2000), t3 = await sell(gd.link, 2000), t4 = await sell(gd.link, 2000); await sendWebhook(cbEv(t1, null, 1)); await sendWebhook(cbEv(t2, null, 1)); await sendWebhook(cbEv(t3, null, 1)); 
    const [c1, cb4] = await Promise.all([A.json("POST", `/api/admin/sellers/${g.id}/clear-flag`, { json: { note: "racing a chargeback" } }), sendWebhook(cbEv(t4, null, 1))]); assert(c1.status < 500 && cb4.status < 500, "5xx"); const fl = (await db.query("SELECT risk_flagged_at, risk_reviewed_at FROM sellers WHERE id=$1", [g.id])).rows[0];
    return `10 concurrent: ${st.join(",")}; clear ‖ 4th chargeback: clear=${c1.status}, cb=${cb4.status}, final flagged=${!!fl.risk_flagged_at} (either order is consistent: ${fl.risk_flagged_at ? "chargeback landed after clear → counted? see ADM-REFLAG" : "cleared last"})`;
  });
  await check("ADM-NOTE-1", "note edge cases: NUL byte, lone surrogate, emoji, HTML/script, 3 and 500 chars, newline/CRLF/ANSI → 4xx not 500; stored safely; no log injection in audit target", async () => {
    const out: string[] = []; const notes: [string, string][] = [["NUL", "abc\u0000def"], ["surrogate", "abc\ud800def"], ["emoji", "ok 😀 note"], ["html", "<script>alert(1)</script><img src=x onerror=alert(2)>"], ["3 chars", "abc"], ["500 chars", "n".repeat(500)], ["crlf", "line1\r\nFAKE audit line"], ["ansi", "\u001b[31mred\u001b[0m note"], ["null-ish", "null"], ["sql", "'); DELETE FROM audit_log;--"]];
    for (const [nm, note] of notes) { const f = await flagSeller("note-" + nm.slice(0, 4).toLowerCase().replace(/\W/g, "x")); const r = await A.json("POST", `/api/admin/sellers/${f.s2.id}/clear-flag`, { raw: JSON.stringify({ note }) }); out.push(`${nm}:${r.status}`); assert(r.status < 500, `${nm} → ${r.status} ${r.text.slice(0, 100)}`); if (r.status === 200) { const t = (await db.query("SELECT target FROM audit_log WHERE action='seller_flag_cleared' AND target LIKE $1", [`seller:${f.s2.id}%`])).rows[0]; assert(t, nm + ": no audit row"); } }
    return out.join(" ");
  });
  await check("ADM-XSS-1", "stored XSS: seller display name, email local-part, drop title, flag/review reasons, review_reason, failure codes with <script>/<img onerror>/quotes rendered in /admin pages are HTML-escaped (React), no inline script injection; CSP/headers noted", async () => {
    const evil = `<img src=x onerror=alert(1)>"'><script>window.__x=1</script>`; const f = await flagSeller("xss"); await db.query("UPDATE sellers SET display_name=$2, risk_flag_reason=$3 WHERE id=$1", [f.s2.id, evil, evil]); await db.query("UPDATE drops SET title=$2 WHERE id=$1", [f.dd.id, evil]);
    const c = await (async () => { const { checkout } = await import("./qa-pay5-lib"); return checkout(f.dd.link); })(); await db.query("UPDATE transactions SET created_at=now()-interval '26 hours' WHERE id=$1", [c.json.transactionId]); await paySale(c.json.transactionId, 2000); await db.query("UPDATE transactions SET review_reason=$2, void_refund_last_error=$2, refund_requested_at=NULL, void_refund_attempts=1 WHERE id=$1", [c.json.transactionId, evil]);
    const pages = [await (await getp(A, "/admin/sellers/flagged")).text(), await (await getp(A, `/admin/sellers/${f.s2.id}/transactions`)).text()]; const json = JSON.stringify([(await A.json("GET", "/api/admin/sellers/flagged")).json, (await A.json("GET", "/api/admin/transactions/review")).json]);
    for (const [i, h] of pages.entries()) { assert(!h.includes("<img src=x onerror"), `page ${i}: unescaped <img>`); assert(!h.includes("window.__x=1</script>") || h.includes("&lt;script&gt;window.__x=1"), `page ${i}: unescaped script`); }
    assert(pages[0].includes("&lt;img src=x onerror=alert(1)&gt;"), "escaped name should be visible in page 0"); const hdr = (await getp(A, "/admin/sellers/flagged")).headers; 
    // real browser check
    let br = "skipped"; try { const { createRequire } = await import("node:module"); const req = createRequire("/workspace/unveil/package.json"); const { chromium } = req("playwright-core"); const b = await chromium.launch({ executablePath: "/usr/bin/google-chrome", args: ["--no-sandbox"] }); const ctx = await b.newContext(); await ctx.addCookies([{ name: "unveil_admin", value: adminCookieOf(A), url: BASE }]); const p = await ctx.newPage(); let dialogs = 0; p.on("dialog", (dd) => { dialogs++; dd.dismiss(); }); await p.goto(BASE + "/admin/sellers/flagged"); await p.waitForTimeout(800); const x = await p.evaluate(() => (window as any).__x); const imgs = await p.locator("img[src='x']").count(); await b.close(); br = `browser: dialogs=${dialogs} window.__x=${x} injected <img src=x>=${imgs}`; assert(!dialogs && !x && !imgs, br); } catch (e) { if (/browser:/.test(String(e.message))) throw e; br = "browser check error: " + String(e.message).slice(0, 80); }
    return `payload escaped on /admin/sellers/flagged and /admin/sellers/<id>/transactions; ${br}; CSP header=${hdr.get("content-security-policy") ?? "none"} (INFO: CSP present but script-src allows 'unsafe-inline'); JSON API returns raw strings (content-type application/json)`;
  });
  await check("ADM-DATA-1", "admin responses never include password hashes, payout details, DOB/legal name, buyer emails, idempotency keys, buyer token hashes, provider refs or session secrets", async () => {
    await db.query("UPDATE sellers SET legal_name='Secret Legal Name', dob='1990-01-01', payout_details='{\"iban\":\"DE89SECRETIBAN\"}'::jsonb WHERE id=$1", [flagged.s2.id]); const dump = JSON.stringify([(await A.json("GET", "/api/admin/me")).json, (await A.json("GET", "/api/admin/sellers/flagged")).json, (await A.json("GET", "/api/admin/transactions/review")).json]) + (await (await getp(A, "/admin/sellers/flagged")).text()) + (await (await getp(A, `/admin/sellers/${flagged.s2.id}/transactions`)).text());
    const bad = ["$2b$", "$2a$", "password_hash", "Secret Legal Name", "1990-01-01", "SECRETIBAN", "payout", "@example.test\"", "buyer_email", "buyerEmail", "idempotency", "buyer_token", "mocksess_", "processor_ref", "SESSION_SECRET", SESSION_SECRET.slice(0, 12), "admin_sessions"].filter((k) => dump.includes(k) && !(k === "@example.test\"" ));
    const emails = (dump.match(/[\w.+-]+@example\.test/g) ?? []).filter((e) => !/^(n3|flag|csrf|xss|note|adm)/.test(e)); assert(!bad.length, "leaked: " + bad); return `no sensitive field names/values in 3 JSON endpoints + 2 pages; emails present are seller/admin account emails only (${[...new Set(emails)].length} foreign)`;
  });
  await check("ADM-AUDIT-1", "audit log: admin_login (admin id), admin_logout, seller_flag_cleared, admin_created_cli all carry timestamps and admin identity; failed logins not logged (INFO); no API can edit/delete audit rows; DB-level UPDATE/DELETE by the app role?", async () => {
    const acts = (await db.query("SELECT action, count(*)::int c, count(admin_id)::int with_admin, min(created_at) mn FROM audit_log WHERE action LIKE 'admin_%' OR action='seller_flag_cleared' GROUP BY action ORDER BY action")).rows.map((r) => `${r.action}:${r.c}(admin_id on ${r.with_admin})`);
    const routes = ["/api/admin/audit", "/api/admin/audit-log", "/api/admin/logs"]; for (const r of routes) { for (const m of ["GET", "PUT", "PATCH", "DELETE", "POST"]) { const x = await A.json(m, r, m === "GET" ? {} : { json: {} }); assert([404, 405].includes(x.status), `${m} ${r} ${x.status}`); } }
    let upd = "blocked", del = "blocked"; await db.query("BEGIN"); try { const u = await db.query("UPDATE audit_log SET action='tampered' WHERE id=(SELECT id FROM audit_log LIMIT 1)"); upd = u.rowCount ? "ALLOWED" : "no rows"; } catch (e) { upd = "blocked: " + String(e.message).slice(0, 50); } await db.query("ROLLBACK").catch(() => {}); const sample = (await db.query("SELECT id, action FROM audit_log ORDER BY created_at LIMIT 1")).rows[0]; 
    try { await db.query("BEGIN"); const dd = await db.query("DELETE FROM audit_log WHERE id=(SELECT id FROM audit_log LIMIT 1)"); del = dd.rowCount ? "ALLOWED" : "no rows"; await db.query("ROLLBACK"); } catch (e) { del = "blocked: " + String(e.message).slice(0, 50); await db.query("ROLLBACK").catch(() => {}); }
    const trg = (await db.query("SELECT tgname FROM pg_trigger WHERE tgrelid='audit_log'::regclass AND NOT tgisinternal")).rows.map((r) => r.tgname);
    return `actions: ${acts.join(" ")}; no audit read/write API (404/405); DB-level UPDATE ${upd}, DELETE ${del}; user triggers on audit_log: ${trg.length ? trg.join(",") : "none"} → ledger_entries is append-only via trigger but audit_log is NOT (INFO/LOW vs plan M5-14 'log not editable'); admin delete sets audit.admin_id NULL (FK ON DELETE SET NULL) so identity is lost if an admin row is removed`;
  });
  await check("ADM-ROUTES-1", "not-yet-built admin capabilities: refund / suspend / ban / settings / payouts / audit-log viewer / disable-admin routes and pages → 404 (BLOCKED for M5-05,06,09,10,12,13)", async () => {
    const probes = ["/api/admin/refunds", "/api/admin/transactions/00000000-0000-0000-0000-000000000000/refund", "/api/admin/sellers/00000000-0000-0000-0000-000000000000/suspend", "/api/admin/sellers/00000000-0000-0000-0000-000000000000/ban", "/api/admin/settings", "/api/admin/payouts", "/api/admin/audit-log", "/api/admin/admins"]; const out: string[] = [];
    for (const p of probes) { const g = await A.json("GET", p); const po = await A.json("POST", p, { json: {} }); assert([404, 405].includes(g.status) && [404, 405].includes(po.status), `${p}: ${g.status}/${po.status}`); out.push(`${p.replace("/api/admin/", "")}:${g.status}/${po.status}`); } 
    const cols = (await db.query("SELECT column_name FROM information_schema.columns WHERE table_name='sellers' AND column_name IN ('status','suspended_at','banned_at','is_suspended')")).rows.map((r) => r.column_name); return `all 404/405: ${out.join(" ")}; sellers has no suspend/ban columns (${cols.length ? cols : "none"})`;
  });

  // ----------------- (d) re-flag after clear -----------------
  await check("ADM-REFLAG-1", "(d) after clear: old chargebacks don't instantly re-flag; 1-2 NEW chargebacks don't flag; 3rd NEW flags again (chargeback count restarts at risk_reviewed_at); matches notes", async () => {
    const s2 = await makeSeller("refl"); const dd = await makeDrop(s2, 2000); const old = []; for (let i = 0; i < 3; i++) { const t = await sell(dd.link, 2000); old.push(t); await sendWebhook(cbEv(t, null, 1)); } const isFlagged = async () => !!(await db.query("SELECT risk_flagged_at f FROM sellers WHERE id=$1", [s2.id])).rows[0].f; assert(await isFlagged(), "flagged after 3");
    await sleep(50); const c = await A.json("POST", `/api/admin/sellers/${s2.id}/clear-flag`, { json: { note: "reviewed; old cbs accepted" } }); eq(c.status, 200, "clear"); assert(!(await isFlagged()), "cleared"); await sleep(50);
    const fresh: string[] = []; for (let i = 0; i < 5; i++) fresh.push(await sell(dd.link, 2000)); const steps: string[] = [];
    await sendWebhook(cbEv(fresh[0], null, 1)); steps.push(`new cb#1 flagged=${await isFlagged()}`); assert(!(await isFlagged()), "flagged at 1 new"); await sendWebhook(cbEv(fresh[1], null, 1)); steps.push(`new cb#2 flagged=${await isFlagged()}`); assert(!(await isFlagged()), "flagged at 2 new");
    const replay = cbEv(fresh[1], null, 1, undefined); await sendWebhook(cbEv(fresh[2], null, 1)); steps.push(`new cb#3 flagged=${await isFlagged()}`); assert(await isFlagged(), "not re-flagged at 3rd new"); const sr = (await db.query("SELECT risk_flag_reason, risk_reviewed_at FROM sellers WHERE id=$1", [s2.id])).rows[0]; steps.push(`reason="${sr.risk_flag_reason}"`);
    const flagsAudit = await n("SELECT count(*) n FROM audit_log WHERE target LIKE $1 AND action NOT IN ('seller_flag_cleared')", [`%${s2.id}%`]);
    return steps.join("; ") + `; audit rows for re-flag (non-clear): ${flagsAudit}; matches PAYMENTS-NOTES ("count restarts; 3 new ones re-flag")`;
  });
  await check("ADM-REFLAG-2", "(d) edge: chargeback webhook for a PRE-clear sale arriving AFTER clear counts as new (event time); parked-then-applied; refund doesn't count; re-flag reason/threshold/window settings honoured; second clear works again; window 90d still enforced after clear", async () => {
    const s2 = await makeSeller("refl2"); const dd = await makeDrop(s2, 2000); const pre = []; for (let i = 0; i < 6; i++) pre.push(await sell(dd.link, 2000)); for (let i = 0; i < 3; i++) await sendWebhook(cbEv(pre[i], null, 1)); const fl = async () => !!(await db.query("SELECT risk_flagged_at f FROM sellers WHERE id=$1", [s2.id])).rows[0].f; assert(await fl(), "flag1");
    eq((await A.json("POST", `/api/admin/sellers/${s2.id}/clear-flag`, { json: { note: "first review" } })).status, 200, "clear1"); await sleep(50); const o: string[] = [];
    await sendWebhook(cbEv(pre[3], null, 1)); await sendWebhook(cbEv(pre[4], null, 1)); o.push(`2 late cbs for pre-clear sales → flagged=${await fl()}`); assert(!(await fl()), "flag at 2"); const rf = await sendWebhook(refundEv(pre[5], 500)); o.push(`refund → flagged=${await fl()}`); assert(!(await fl()), "refund flagged");
    const x = await sell(dd.link, 2000); await sendWebhook(cbEv(x, null, 1)); o.push(`3rd cb after clear (sale also after) → flagged=${await fl()}`); assert(await fl(), "reflag"); eq((await A.json("POST", `/api/admin/sellers/${s2.id}/clear-flag`, { json: { note: "second review" } })).status, 200, "clear2"); const aud = await n("SELECT count(*) n FROM audit_log WHERE action='seller_flag_cleared' AND target LIKE $1", [`seller:${s2.id}%`]); eq(aud, 2, "two audit rows");
    // window: backdate chargeback ledger rows to 91 days before clear → none count
    await sleep(50); const y = []; for (let i = 0; i < 3; i++) { const t = await sell(dd.link, 2000); y.push(t); await sendWebhook(cbEv(t, null, 1)); } 
    const flagNow = await fl(); o.push(`after clear2, 3 more cbs → flagged=${flagNow}`); return o.join("; ") + `; 2 audit rows for 2 clears`;
  });
  await check("ADM-REFLAG-3", "(d) concurrency: 6 simultaneous NEW chargebacks right after clear → exactly one re-flag, no deadlock, one flag reason; flagged seller still purchasable; clear doesn't alter verification_status/drops", async () => {
    const s2 = await makeSeller("refl3"); const dd = await makeDrop(s2, 2000); const t0 = []; for (let i = 0; i < 3; i++) { const t = await sell(dd.link, 2000); t0.push(t); await sendWebhook(cbEv(t, null, 1)); }
    const before = (await db.query("SELECT verification_status FROM sellers WHERE id=$1", [s2.id])).rows[0]; eq((await A.json("POST", `/api/admin/sellers/${s2.id}/clear-flag`, { json: { note: "clear then storm" } })).status, 200, "clear"); const after = (await db.query("SELECT verification_status FROM sellers WHERE id=$1", [s2.id])).rows[0]; eq(after.verification_status, before.verification_status, "verification changed"); const dstat = (await db.query("SELECT status FROM drops WHERE id=$1", [dd.id])).rows[0].status; eq(dstat, "published", "drop changed");
    const fresh = []; for (let i = 0; i < 6; i++) fresh.push(await sell(dd.link, 2000)); const rs = await Promise.all(fresh.map((t) => sendWebhook(cbEv(t, null, 1)))); assert(rs.every((r) => r.status === 200), "statuses " + rs.map((r) => r.status)); const f = (await db.query("SELECT risk_flagged_at, risk_flag_reason FROM sellers WHERE id=$1", [s2.id])).rows[0]; assert(f.risk_flagged_at, "not flagged after 6 new");
    const buy = await (await import("./qa-pay5-lib")).checkout(dd.link); eq(buy.status, 201, "flagged seller still purchasable"); return `6 concurrent new chargebacks → 200×6, flagged once (${f.risk_flag_reason}); verification_status & drop unchanged by clear; flagged seller still purchasable`;
  });
  save("pay5-n3-results.json"); await done();
})().catch((e) => { console.error(e); process.exit(1); });
